### ISSUE TITLE
More information error when `quarto_run()` fails

### ISSUE THREAD

**Issue by hadley** [quarto-dev/quarto-r#184]
I think you can take the same approach as pkgdown does with rmarkdown, i.e. if it fails and it's in quiet mode, you can still print the appropriate part of the stderr that callr has captured.

(It doesn't matter too much here, but in general when you're wrapping errors, you should always use `withCallingHandlers` not `tryCatch`)

```R

  path <- withCallingHandlers(
    callr::r_safe(rmarkdown_render_with_seed, args = args, show = !quiet),
    error = function(cnd) wrap_rmarkdown_error(cnd, input_file, call)
  )

wrap_rmarkdown_error <- function(cnd, input, call = caller_env()) {
  lines <- strsplit(gsub("^\r?\n", "", cnd$stderr), "\r?\n")[[1]]
  lines <- lines[nchar(lines) > 0]
  # Feeding random text back into cli, so have to escape
  lines <- gsub("{", "{{", lines, fixed = TRUE)
  lines <- gsub("}", "}}", lines, fixed = TRUE)

  cli::cli_abort(
    c(
      "!" = "Failed to render {.path {input}}.",
      set_names(lines, "x")
    ),
    parent = cnd$parent %||% cnd,
    trace = cnd$parent$trace,
    call = call
  )
}

**Comment by cderv** [comment]
> (It doesn't matter too much here, but in general when you're wrapping errors, you should always use withCallingHandlers not tryCatch)

Thanks for the suggestion. I did switch to `withCallingHandler` now

> I think you can take the same approach as pkgdown does with rmarkdown, i.e. if it fails and it's in quiet mode, you can still print the appropriate part of the stderr that callr has captured.

Do you have some usage where you found lack of information in error ? Is it always when `quiet = TRUE` ? 

I think I may need to change the way `processx::run()` is used. 🤔 I see in **pkgdown** you are using `callr::r_safe()` with `show = !quiet` - so I understand that even if `quiet = TRUE`, you'll still have error information from `rmarkdown::render()` background code, because **callr** will handle the "show it or not" part. 

Here, when `quiet = TRUE` in `quarto_run()`, this is setting the `--quiet` flag in Quarto. And it happens that Quarto will not print any message to stderr at all. 

`````
❯ quarto render not-existing --quiet

❯ echo $LASTEXITCODE
1

❯ quarto render not-existing
ERROR: No valid input files passed to render

Stack trace:
    at Command.actionHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:288:13)
    at eventLoopTick (ext:core/01_core.js:178:7)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:193:5)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:225:5
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/main.ts:45:14
    at async mainRunner (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/main.ts:47:5)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:215:3

❯ echo $LASTEXITCODE
1
`````

Exit code is correctly a failure (1 and not 0), but nothing is shown. 

So in the current implementation, I don't think I can show more. I just added already a helper message to warn user about this. 

``` r
quarto::quarto_render("not-existing", quiet = TRUE)
#> Error in `quarto::quarto_render()`:
#> ✖ Error running quarto cli.
#> ℹ Rerun with `quiet = FALSE` to see the full error message.
#> Caused by error:
#> ! System command 'quarto.exe' failed
```

So I am thinking that if we want to be more verbose, `--quiet` should not be passed to Quarto, but rather it should be `processx::run(echo = !quiet)` 🤔 

Am I correct ? 

Did you have another case where it does not involve `--quiet` ? 

Thank you

**Comment by hadley** [comment]
I have forgotten the motivating case, but your analysis sounds correct to me.
